global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:9090']
    scrape_interval: 5s
    metrics_path: '/metrics'

  - job_name: 'api-gateway-health'
    static_configs:
      - targets: ['api-gateway:8080']
    scrape_interval: 30s
    metrics_path: '/health'

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
