server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s
  tls:
    enabled: false
    cert_file: ""
    key_file: ""

redis:
  addr: "localhost:6379"
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 2

auth:
  jwt_secret: "your-super-secret-jwt-key-change-in-production"
  token_expiry: 24h
  refresh_expiry: 168h # 7 days
  issuer: "api-gateway"

logging:
  level: "info"
  format: "json"
  output: "logs/gateway.log"
  max_size: 100
  max_backups: 3
  max_age: 28

metrics:
  enabled: true
  path: "/metrics"
  port: 9090

routes:
  - path: "/api/v1/users"
    method: "GET"
    backends:
      - url: "http://localhost:3001"
        weight: 2
        max_connections: 100
        health_check:
          enabled: true
          path: "/health"
          interval: 30s
          timeout: 5s
        timeout: 30s
      - url: "http://localhost:3002"
        weight: 1
        max_connections: 100
        health_check:
          enabled: true
          path: "/health"
          interval: 30s
          timeout: 5s
        timeout: 30s
    auth_required: true
    rate_limit: 100
    cache_enabled: true
    cache_ttl: 5m
    timeout: 30s
    retries: 3
    load_balancer: "weighted_round"
    middleware: ["auth", "rate_limit", "cache"]

  - path: "/api/v1/orders"
    method: "GET"
    backends:
      - url: "http://localhost:3003"
        weight: 1
        max_connections: 50
        health_check:
          enabled: true
          path: "/health"
          interval: 30s
          timeout: 5s
        timeout: 30s
    auth_required: true
    rate_limit: 50
    cache_enabled: false
    timeout: 30s
    retries: 3
    load_balancer: "round_robin"
    middleware: ["auth", "rate_limit"]

  - path: "/api/v1/products"
    method: "GET"
    backends:
      - url: "http://localhost:3004"
        weight: 1
        max_connections: 100
        health_check:
          enabled: true
          path: "/health"
          interval: 30s
          timeout: 5s
        timeout: 30s
      - url: "http://localhost:3005"
        weight: 1
        max_connections: 100
        health_check:
          enabled: true
          path: "/health"
          interval: 30s
          timeout: 5s
        timeout: 30s
    auth_required: false
    rate_limit: 200
    cache_enabled: true
    cache_ttl: 10m
    timeout: 30s
    retries: 3
    load_balancer: "least_conn"
    middleware: ["rate_limit", "cache"]

  - path: "/api/v1/public"
    method: "GET"
    backends:
      - url: "http://localhost:3006"
        weight: 1
        max_connections: 200
        health_check:
          enabled: true
          path: "/health"
          interval: 30s
          timeout: 5s
        timeout: 30s
    auth_required: false
    rate_limit: 1000
    cache_enabled: true
    cache_ttl: 15m
    timeout: 30s
    retries: 2
    load_balancer: "ip_hash"
    middleware: ["rate_limit", "cache"]
